### ISSUE TITLE
More features when using the commandline arguments

### ISSUE THREAD

**Issue by olpeh** [olpeh/wht#44]
## Todo
- [x] Starting
- [x] Stopping
- [ ] Possibility to select project
- [ ] Possibility to select task
- [ ] Possibility to set description
- [ ] Possibility to save using last entered specs
- [ ] Fix an issue that causes breakduration to become -1
- [ ] Allow only one instance of the app to run
